
package ws.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WsServiceTest", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsServiceTest {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://ws/", className = "ws.client.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://ws/", className = "ws.client.HelloWorldResponse")
    @Action(input = "http://ws/WsServiceTest/HelloWorldRequest", output = "http://ws/WsServiceTest/HelloWorldResponse")
    public String helloWorld();

}
